import {
  Plus,
  Trash2,
  Pencil,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Check,
  X,
  AlertTriangle,
  Info,
  CheckCircle,
  XCircle,
  Circle,
  Home,
  CreditCard,
  PieChart,
  Settings,
  LogOut,
  User,
  Wallet,
  ArrowUpRight,
  ArrowDownLeft,
  Search,
  Menu,
  Eye,
  EyeOff,
  Loader2,
  AlertCircle,
  ShoppingCart,
  Truck,
  ShoppingBag,
  ArrowDownCircle,
  ArrowUpCircle,
  Tag,
  Repeat,
  Inbox,
  DollarSign,
  Target,
  TrendingUp,
  TrendingDown,
  BarChart2,
  Filter,
  Calendar,
  RefreshCw,
  LayoutDashboard,
  ArrowLeftRight,
  PiggyBank,
  PlusCircle,
  Bell,
  Coins,
  Mail,
  Lock,
  Sun,
  Moon,
  Palette,
  Shield,
  Layers,
  Zap,
  Droplet,
  Flame,
  Wifi,
  Utensils,
  Coffee,
  Pizza,
  Car,
  Bus,
  Train,
  Plane,
  Bike,
  Heart,
  Stethoscope,
  Pill,
  Activity,
  Film,
  Music,
  Gamepad2,
  Tv,
  Smartphone,
  Laptop,
  Monitor,
  Headphones,
  Wrench,
  Hammer,
  Scissors,
  Gift,
  Shirt,
  Building,
  Store,
  Hospital,
  School,
  Briefcase,
  Camera,
  Book,
  Map,
  Percent,
} from 'lucide-react';

export const iconRegistry = {
  plus: Plus,
  trash: Trash2,
  pencil: Pencil,
  edit: Pencil,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  check: Check,
  x: X,
  'alert-triangle': AlertTriangle,
  info: Info,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  circle: Circle,
  home: Home,
  'credit-card': CreditCard,
  'pie-chart': PieChart,
  settings: Settings,
  'log-out': LogOut,
  user: User,
  wallet: Wallet,
  'arrow-up-right': ArrowUpRight,
  'arrow-down-left': ArrowDownLeft,
  search: Search,
  menu: Menu,
  eye: Eye,
  'eye-off': EyeOff,
  'loader-2': Loader2,
  'alert-circle': AlertCircle,
  'shopping-cart': ShoppingCart,
  truck: Truck,
  'shopping-bag': ShoppingBag,
  'arrow-down-circle': ArrowDownCircle,
  'arrow-up-circle': ArrowUpCircle,
  tag: Tag,
  repeat: Repeat,
  inbox: Inbox,
  'dollar-sign': DollarSign,
  target: Target,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'bar-chart-2': BarChart2,
  filter: Filter,
  calendar: Calendar,
  'refresh-cw': RefreshCw,
  'layout-dashboard': LayoutDashboard,
  'arrow-left-right': ArrowLeftRight,
  'piggy-bank': PiggyBank,
  'plus-circle': PlusCircle,
  bell: Bell,
  coins: Coins,
  mail: Mail,
  lock: Lock,
  sun: Sun,
  moon: Moon,
  palette: Palette,
  shield: Shield,
  layers: Layers,
  zap: Zap,
  droplet: Droplet,
  flame: Flame,
  wifi: Wifi,
  utensils: Utensils,
  coffee: Coffee,
  pizza: Pizza,
  car: Car,
  bus: Bus,
  train: Train,
  plane: Plane,
  bike: Bike,
  heart: Heart,
  stethoscope: Stethoscope,
  pill: Pill,
  activity: Activity,
  film: Film,
  music: Music,
  'gamepad-2': Gamepad2,
  tv: Tv,
  smartphone: Smartphone,
  laptop: Laptop,
  monitor: Monitor,
  headphones: Headphones,
  wrench: Wrench,
  hammer: Hammer,
  scissors: Scissors,
  gift: Gift,
  shirt: Shirt,
  building: Building,
  store: Store,
  hospital: Hospital,
  school: School,
  briefcase: Briefcase,
  camera: Camera,
  book: Book,
  map: Map,
  percent: Percent,
} as const;

export type IconName = keyof typeof iconRegistry;
