import {
  Plus,
  Trash2,
  Pencil,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Check,
  X,
  AlertTriangle,
  Info,
  CheckCircle,
  XCircle,
  Home,
  CreditCard,
  PieChart,
  Settings,
  LogOut,
  User,
  Wallet,
  ArrowUpRight,
  ArrowDownLeft,
  Search,
  Menu,
  Eye,
  EyeOff
} from 'lucide-react';

export const iconRegistry = {
  plus: Plus,
  trash: Trash2,
  pencil: Pencil,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  check: Check,
  x: X,
  'alert-triangle': AlertTriangle,
  info: Info,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  home: Home,
  'credit-card': CreditCard,
  'pie-chart': PieChart,
  settings: Settings,
  'log-out': LogOut,
  user: User,
  wallet: Wallet,
  'arrow-up-right': ArrowUpRight,
  'arrow-down-left': ArrowDownLeft,
  search: Search,
  menu: Menu,
  eye: Eye,
  'eye-off': EyeOff,
} as const;

export type IconName = keyof typeof iconRegistry;
